id: P009308
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20418
  title: བོད་ཀྱི་རྩོམ་རིག་བྱུང་འཕེལ་གྱི་ལོ་རྒྱུས་དང་ཁྱད་ཆོས།
  author: ''
  volumes:
    cc972170814a4ed6a7257add8731f035:
      image_group_id: I1KG23000
      title: ''
      volume_number: 1
      total_pages: 412
      base_file: v001.txt
